### PR TITLE
Cls 17 18 student becomes the teacher

### PR DESCRIPTION
**Pull request by 09041985**

### CODE REVIEW

**Comment by dmitrytokarev** [comment]
@09041985 please fix the build failures for Python 3.6
```
>               assert e.message == "{} Passed the wrong data type".format(input_neg)
E               AttributeError: 'TypeError' object has no attribute 'message'
```

**Comment by dmitrytokarev** [comment]
@09041985 i truly encourage you to simplify the error message - you can just pass some static strings (no formatting) and that will be just fine. We need to get this task completed. You made tremendous progress so this little thing with the error message formatting is just a pain in the butt, don't let it stand on your way to become great test automation engineer. Let's just move on!

**Comment by 09041985** [comment]
@dmitrytokarev I had to add one more quotation marks, since the bug was reproduced even after the removal of format()

**Comment by dmitrytokarev** [comment]
@09041985 that sounds like a bug in Python.
Can you create a bug in Jira with link to this PR - and assign it to me

**Comment by dmitrytokarev** [comment]
Oh, you have update the branch first then merge

**Pull request merged**
